name: example
description: Example app for data_class_plugin
version: 1.0.0
publish_to: "none"
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  data_class_plugin:
    path: ../

dev_dependencies:
  lints: 2.0.0
  test: 1.21.6
