version: 2
enable-beta-ecosystems: true

updates:
  - package-ecosystem: "github-actions"
    directory: "."
    schedule:
      interval: "monthly"

  - package-ecosystem: "pub"
    directory: "./package"
    schedule:
      interval: "monthly"
    versioning-strategy: increase

  - package-ecosystem: "pub"
    directory: "./examples/file_generation_mode"
    schedule:
      interval: "monthly"
    versioning-strategy: increase

  - package-ecosystem: "pub"
    directory: "./examples/in_place_mode"
    schedule:
      interval: "monthly"
    versioning-strategy: increase

  - package-ecosystem: "pub"
    directory: "./package/tools/analyzer_plugin"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
