name: in_place_mode
description: Example app for data_class_plugin
version: 1.0.0
publish_to: "none"
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  data_class_plugin:
    path: ../../package

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
