include: package:lints/recommended.yaml

analyzer:
  plugins:
    - data_class_plugin

linter:
  rules:
    - always_specify_types
    - always_use_package_imports
    - prefer_const_constructors
    - prefer_const_declarations
