name: data_class_plugin
version: 0.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  analyzer: 5.2.0
  analyzer_plugin: 0.11.2
  meta: 1.8.0
  yaml: 3.1.1
  glob: 2.1.1
  path: 1.8.2
  file: 6.1.4

dev_dependencies:
  lints: 2.0.1
  test: 1.22.0
  dart_style: 2.2.4
