name: data_class_plugin_loader
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  data_class_plugin:
    git:
      url: https://github.com/spideythewebhead/dart_data_class_plugin.git
      ref: main
# dependency_overrides:
#   data_class_plugin:
#     path: /absolute/path/to/project
