name: data_class_plugin_loader
version: 0.0.1
publish_to: "none"

homepage: https://github.com/spideythewebhead/dart_data_class_plugin
repository: https://github.com/spideythewebhead/dart_data_class_plugin

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  data_class_plugin: 0.2.0
