name: file_generation_mode
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  data_class_plugin:
    path: ../../package

dev_dependencies:
  lints: ^2.1.0
  tachyon: ^0.0.6
  test: ^1.24.5
