name: Publish Package

on:
  release: [published]

jobs:
  validate-plugin:
    uses: ./.github/workflows/validate_plugin.yml
    with:
      working_directory: ./

  package-analysis:
    runs-on: ubuntu-latest
    needs: validate-plugin
    steps:
      - uses: actions/checkout@v3

      - uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: 📊 Check scores
        env:
          TOTAL: ${{ steps.analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
        run: |
          PERCENTAGE=$(( $TOTAL * 100 / $TOTAL_MAX ))
          if (( $PERCENTAGE < 90 ))
          then
            echo Score too low!
            exit 1
          fi

  release:
    runs-on: ubuntu-latest
    needs: package-analysis
    container:
      image:  dart:latest

    steps:
      - name: ⚙ Setup Pub Credentials
        shell: bash
        env:
          PUB_DEV_PUBLISH_ACCESS_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_ACCESS_TOKEN }}
          PUB_DEV_PUBLISH_REFRESH_TOKEN: ${{ secrets.PUB_DEV_PUBLISH_REFRESH_TOKEN }}
          PUB_DEV_PUBLISH_TOKEN_ENDPOINT: ${{ secrets.PUB_DEV_PUBLISH_TOKEN_ENDPOINT }}
          PUB_DEV_PUBLISH_EXPIRATION: ${{ secrets.PUB_DEV_PUBLISH_EXPIRATION }}
        run: |
          sh ./pub_login.sh

      - name: 🔎 Check Publish Warnings
        run: pub publish --dry-run

      - name: 🚀 Publish Package
        run: pub publish -f
